version: '3.8'

services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.3.0
        container_name: keycloak
        command: start-dev
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
            KC_DB: postgres
            KC_DB_URL_HOST: keycloak-db
            KC_DB_URL_DATABASE: keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: keycloak
        ports:
            - '8080:8080'
        depends_on:
            - keycloak-db
        restart: unless-stopped

    keycloak-db:
        image: postgres:15-alpine
        container_name: keycloak-db
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: keycloak
        ports:
            - '5432:5432'
        volumes:
            - keycloak-db-data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    keycloak-db-data:
